###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "user1",
    "email": "test6@gmail.com",
    "password": "test0123",
    "roles": "admin"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test6@gmail.com",
    "password": "test0123"
}
###
POST http://localhost:3000/createapp
Content-Type: application/json

{
    "applicationName" : "rs1",
    "whitelistedDomains" : ["test@gmail.com"]
}

### 
GET http://localhost:3000/getAllBuckets?apikey=c5cc5ba0e2101354e3ce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YThjY2VhYjc1M2QxOGFkN2U3YWQxMSIsInVzZXJuYW1lIjoiYWEiLCJpYXQiOjE3MDU1NjEzNzl9.UwDMvyXwabbNDlWoEBCQHA72V-PF3BPfR8SMWarn9z8
### 

GET http://localhost:3000/getAllFilesFromParticularBucket?apikey={api}
Authorization: Bearer {token}

###
POST http://localhost:3000/upload?&folderName={bucketName}
