###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "<user>",
    "email": "<email>",
    "password": "<pass>",
    "roles": "<role>"
}

###
POST http://localhost:3000/auth/login?apiKey={api}
Content-Type: application/json

{
    "email": "<email>",
    "password": "<pass>"
}
###
POST http://localhost:3000/createapp?apiKey={api}
Content-Type: application/json
Authorization: Bearer {token}


{
    "folderName" : "<name of bucket>"
}

### 
GET http://localhost:3000/getAllBuckets?apikey={api}
Authorization: Bearer {token}
### 

GET http://localhost:3000/getAllFilesFromParticularBucket?apikey={api}
Authorization: Bearer {token}

###
POST http://localhost:3000/upload?apiKey={api}&folderName={bucketName}
